// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI uses file URL for generate; runtime uses libsql adapter (see src/lib/prisma.ts)
  datasource: {
    url: "file:./dev.db",
  },
});
